name: My first workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu:latest
    steps:
    - name: Welcome message
      run: echo "My first job"

    - name: List of files
      run: ls
      